default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clonesns_development
test:
  <<: *default
  database: clonesns_test

production:
  <<: *default
  database: clonesns_production
  username: clonesns
  password: <%= ENV['CLONESNS_DATABASE_PASSWORD'] %>
